# orders for the figure showing the errors on (r, b)
error_orders = [20,100,500]
time_orders = [20, 40, 60, 100, 200, 350, 500]
Ns = [100, 500, 1000, 5000, 10000] #50000, 100000]

rule flux_starry:
    output:
        "data/flux_starry_{N}.npz"
    script:
        "scripts/flux_starry.py"


rule flux_jaxoplanet:
    input:
        "data/flux_starry_{N}.npz"
    output:
        "data/flux_jaxoplanet_{N}_{order}.npz"
    script:
        "scripts/flux_jaxoplanet.py"


rule plot_error_n:
    input:
        starry = "data/flux_starry_500.npz",
        jaxoplanet = [f"data/flux_jaxoplanet_500_{order}.npz" for order in error_orders]
    output:
        "figures/error_n.png"
    params:
        orders=error_orders
    script:
        "scripts/plot_error_n.py"

rule plot_time_n:
    input:
        starry_1000 = "data/flux_starry_1000.npz",
        jaxoplanet_1000 = [f"data/flux_jaxoplanet_1000_{order}.npz" for order in time_orders],
    output:
        "figures/time_n.pdf"
    params:
        orders=time_orders
    script:
        "scripts/plot_time_n.py"

rule plot_time_NN:
    input:
        starry = [f"data/flux_starry_{N}.npz" for N in Ns],
        jaxoplanet = [f"data/flux_jaxoplanet_{N}_500.npz" for N in Ns]
    output:
        "figures/time_NN.pdf"
    params:
        Ns=Ns
    script:
        "scripts/plot_time_NN.py"