import numpy as np


orders = (np.ceil(np.exp(np.linspace(np.log(20), np.log(500), 8)) / 10) * 10).astype(int)
Ns = np.logspace(2, 5, 8).astype(int)

radius = 0.1
u = (1.0,1.0)

rule all:
    input:
        "figures/speed_vs_order.pdf",
        "figures/speed_vs_N.pdf"


rule flux_starry:
    output:
        "data/flux_starry_{lmax}_{N}_{radius}.npz"
    params:
        u = u
    script:
        "scripts/flux_starry.py"



rule flux_exoplanet_quadratic:
    output:
        "data/flux_exoplanet_{N}_{radius}.npz"
    params:
        u = u
    script:
        "scripts/flux_exoplanet_quadratic.py"


rule flux_jaxoplanet:
    output:
        "data/flux_jaxoplanet_{lmax}_{N}_{order}_{radius}.npz"
    params:
        u = u,
    script:
        "scripts/flux_jaxoplanet.py"


rule plot_error_vs_order:
    input:
        starry_quadratic = "data/flux_starry_quadratic_10000_{radius}.npz",
        jaxoplanet_quadratic = [f"data/flux_jaxoplanet_quadratic_10000_{order}_{radius}.npz" for order in orders],
        jaxoplanet_quadratic_gpu = [f"static/gpu/flux_jaxoplanet_quadratic_10000_{order}_{radius}.npz" for order in orders],
        exoplanet_quadratic = "data/flux_exoplanet_quadratic_10000_{radius}.npz",
        starry_l20 = "data/flux_starry_l20_10000_{radius}.npz",
        jaxoplanet_l20 = [f"data/flux_jaxoplanet_l20_10000_{order}_{radius}.npz" for order in orders],
        jaxoplanet_l20_gpu = [f"static/gpu/flux_jaxoplanet_l20_10000_{order}_{radius}.npz" for order in orders]
    output:
        "figures/speed_vs_order.pdf"
    params:
        orders=orders
    script:
        "scripts/plot_error_vs_order.py"

fixed_order_quad = 100
fix_order_l20 = 200

rule flux_all_single_b:
    params:
        orders=orders,
        u = u
    output:
        "data/flux_all_single_b_{radius}.pickle"
    script:
        "scripts/flux_all_single_b.py"

rule plot_error_vs_N:
    input:
        starry_quadratic = [f"data/flux_starry_None_{N}_{radius}.npz" for N in Ns],
        jaxoplanet_quadratic = [f"data/flux_jaxoplanet_None_{N}_{fixed_order_quad}_{radius}.npz" for N in Ns],
        jaxoplanet_quadratic_gpu = [f"static/gpu/flux_jaxoplanet_quadratic_{N}_{fixed_order_quad}_{radius}.npz" for N in Ns],
        exoplanet_quadratic = [f"data/flux_exoplanet_{N}_{radius}.npz" for N in Ns],
        starry_l20 = [f"data/flux_starry_20_{N}_{radius}.npz" for N in Ns],
        jaxoplanet_l20 = [f"data/flux_jaxoplanet_20_{N}_{fix_order_l20}_{radius}.npz" for N in Ns],
        jaxoplanet_l20_gpu = [f"static/gpu/flux_jaxoplanet_20_{N}_{fix_order_l20}_{radius}.npz" for N in Ns]
    output:
        "figures/speed_vs_N.pdf"
    params:
        Ns=Ns,
        order_l20=fix_order_l20,
        order_quad=fixed_order_quad
    script:
        "scripts/plot_speed_vs_N.py"

trappist_radius = 0.1
trappist_order = 10
hd_order = 10

rule plot_error_vs_N_realistic:
    input:
        jaxoplanet_quadratic = [f"data/flux_jaxoplanet_None_{N}_{trappist_order}_{trappist_radius}.npz" for N in Ns],
        jaxoplanet_quadratic_gpu = [f"static/gpu_single_core/flux_jaxoplanet_None_{N}_{trappist_order}_{trappist_radius}.npz" for N in Ns],
        exoplanet_quadratic = [f"data/flux_exoplanet_{N}_{trappist_radius}.npz" for N in Ns],
        starry_l3 = [f"data/flux_starry_3_{N}_{trappist_radius}.npz" for N in Ns],
        jaxoplanet_l3 = [f"data/flux_jaxoplanet_3_{N}_{hd_order}_{trappist_radius}.npz" for N in Ns],
        jaxoplanet_l3_gpu = [f"static/gpu_single_core/flux_jaxoplanet_3_{N}_{hd_order}_{trappist_radius}.npz" for N in Ns]
    output:
        "figures/speed_vs_N_realistic.pdf"
    params:
        Ns=Ns,
        order_l20=hd_order,
        order_quad=trappist_order
    script:
        "scripts/plot_speed_vs_N_realistic.py"
